# http 代理配置,根据服务网络情况自行开启
codingapi.okx.proxy.enable-proxy=false
codingapi.okx.proxy.proxy-host=127.0.0.1
codingapi.okx.proxy.proxy-port=7890
codingapi.okx.proxy.proxy-type=http

# OKX api 参数配置
codingapi.okx.config.apikey=dcd08b32-9450-4100-bc83-a989feadaed4
codingapi.okx.config.secretkey=35DC54ED1F023E51F082CC6AF8985342
codingapi.okx.config.passphrase=~89*0374~6512*aI
codingapi.okx.config.mock=false

# QQ Bot 配置
qqbot.enabled=true
qqbot.appId=1903919041
qqbot.clientSecret=hChDjGnLuT3dEpR3gKydIyeL2kSBuePA
qqbot.async=true
qqbot.realData=true
qqbot.resultLimit=3

# 群记事本机器人配置
# 功能：监听群消息，同步发送作品清单记事本
# 提取作品时自动设置 vipok=3 推送到队列
group.notepad.bot.token=8766973549:AAFKJb6cNz3WIB31mdLnsBMxH6s8BVZJdIM
group.notepad.target.group=-1003205013648
group.notepad.target.group2=-1003173512543
