# http 代理配置,根据服务网络情况自行开启
codingapi.okx.proxy.enable-proxy=false
codingapi.okx.proxy.proxy-host=127.0.0.1
codingapi.okx.proxy.proxy-port=7890
codingapi.okx.proxy.proxy-type=http

# OKX api 参数配置
codingapi.okx.config.apikey=dcd08b32-9450-4100-bc83-a989feadaed4
codingapi.okx.config.secretkey=35DC54ED1F023E51F082CC6AF8985342
codingapi.okx.config.passphrase=~89*0374~6512*aI
codingapi.okx.config.mock=false

# QQ Bot 配置
qqbot.enabled=false
qqbot.appId=
qqbot.clientSecret=
qqbot.async=true
qqbot.realData=true
qqbot.resultLimit=3
