# 服务端的IP地址
system.net.sock.ip = 127.0.0.1
#system.net.sock.ip = 103.29.135.214
#system.net.sock.ip = 103.29.134.107
#system.net.sock.ip = 192.168.211.134

# 服务端的检索监听端口
system.net.sock.query.port = 8881
#system.net.sock.query.port = 6666

# 服务端的加载监听端口
system.net.sock.index.port = 8882
#system.net.sock.index.port = 6667



# 系统加载方式是否采用线程自动加载，true表示是线程加载。false表示不是
system.add.byThread = true

# 当格式化文件加载完成后，处理的方式。true表示删除。false表示保留。此项当且仅当加载方式是线程自动加载时有效
system.add.articlefile.del = true

# 一个格式化文件里面存放的文章数量。此项当且仅当加载方式是线程自动加载时有效
system.index.articleNumInOneFile = 100

# 格式化文件的操作目录。此项当且仅当加载方式是线程自动加载时有效
system.index.file.dir = format_file


socket.timeout.second=3000

article.textfield.maxlength.K=200


#SpecialIndex.conf move here
special.index.fieldnames = TX
special.index.TX = [TI][\r\n\t\r\n\t\t\r\n][TX]
